### ISSUE TITLE
Get Goal to remain on page

### ISSUE THREAD

**Issue by romebell** [NykywanP/Hot-Shot#2]
@NykywanP I figured what we can do is write a function called `drawGoal`

```javascript
function drawGoal() {
  let cx = document.querySelector("canvas").getContext("2d");
  let img = document.createElement("img");
  img.src = "https://banner2.cleanpng.com/20180320/qyw/kisspng-backboard-ncaa-men-s-division-i-basketball-tournam-basketball-hoop-png-transparent-5ab1b00c2d0b99.9652717415215943801845.jpg";
  img.addEventListener("load", () => {
    for (let x = 10; x < 200; x += 30) {
      cx.drawImage(img, x, 10);
    }
  });
}
```

**Comment by romebell** [comment]
Then you can run the function `drawGoal` here:
<img width="426" alt="Screen Shot 2020-11-09 at 9 12 39 AM" src="https://user-images.githubusercontent.com/13144457/98573613-e98b5600-226b-11eb-8c25-b5fde41ecfea.png">

**Comment by romebell** [comment]
- [x] Where the goal located?

- [ ] Where is the ball location?
- [x] `cx.drawImage(img, x, 10);`
<details>
<summary>cx.drawImage(img, x, 10);</summary>

`dx`
The x-axis coordinate in the destination canvas at which to place the top-left corner of the source image.
`dy`
The y-axis coordinate in the destination canvas at which to place the top-left corner of the source image.

</details>
<detail>
<summary></summary>
`dx`
The x-axis coordinate in the destination canvas at which to place the top-left corner of the source image.
`dy`
The y-axis coordinate in the destination canvas at which to place the top-left corner of the source image.
</detail>
- [x] `console.log(ball.x);`
- [x] `console.log(cx);`

- [ ] To make it make a  noise

**Comment by NykywanP** [comment]
```js
function drawGoal() {
     let cx = document.querySelector("canvas").getContext("2d");
     let img = document.createElement("img");
     img.src = "https://banner2.cleanpng.com/20180320/qyw/kisspng-backboard-ncaa-men-s-division-i-basketball-tournam-basketball-hoop-png-transparent-5ab1b00c2d0b99.9652717415215943801845.jpg";
     img.addEventListener("load", () => {
       for (let x = 10; x < 200; x += 30) {
         cx.drawImage(img, x, 10);
       }
     });
   }
```

**Comment by romebell** [comment]
- [x] reset button

**Comment by romebell** [comment]
- [ ] `Option` + `down arrow`

**Comment by romebell** [comment]
- [x] `console.log()` the position of the ball
- [x] move the ball position to the goal
- [x] Record the `ball.x` and `ball.y` position

**Comment by NykywanP** [comment]
```JS
{x: 610, y: 245, vx: 5, vy: 1, radius: 40, …}
color: "#C9082A"
draw: ƒ ()
radius: 40
vx: 5
vy: 1
x: 711
y: 318
```
I was able to find the balls location on html canvas via console.log()

**Comment by romebell** [comment]
### This is the `scoreCount()` function
<img width="385" alt="Screen Shot 2020-11-09 at 10 55 39 PM" src="https://user-images.githubusercontent.com/13144457/98640188-e41b2380-22de-11eb-9732-18ee39771bae.png">

Replace this code in your `app.js` with this: 

```js
function scoreCount(ball){
  var score = document.getElementById('score')
  if (655 > ball.x && ball.x > 640) {
    score.textContent = Number(score.textContent) + 1;
  }
  console.log(score);
}
```

**Comment by romebell** [comment]
### Then you need to run the `scoreCount()` function here (2 lines after the call of `drawBall` function): 

<img width="453" alt="Screen Shot 2020-11-09 at 10 53 41 PM" src="https://user-images.githubusercontent.com/13144457/98640529-0614a600-22df-11eb-8568-1dde26f351a9.png">
